package com.au569735.coronatracker.model;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity
public class CountryStatistic {

    @PrimaryKey(autoGenerate = true)
    int uid;
    String country;
    String countryCode;
    int flagIconId;
    int cases;
    int deaths;
    double rating;
    String note;

    public void setUid(int uid) {
        this.uid = uid;
    }

    public int getUid(){
        return uid;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public int getFlagIconId() {
        return flagIconId;
    }

    public void setFlagIconId(int flagIconId) {
        this.flagIconId = flagIconId;
    }

    public int getCases() {
        return cases;
    }

    public void setCases(int cases) {
        this.cases = cases;
    }

    public int getDeaths() {
        return deaths;
    }

    public void setDeaths(int deaths) {
        this.deaths = deaths;
    }

    public double getRating() {
        return rating;
    }

    public void setRating(double rating) {
        this.rating = rating;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public CountryStatistic(String country, String countryCode, int flagIconId, int cases, int deaths, double rating, String note) {
        this.country = country;
        this.countryCode = countryCode;
        this.flagIconId = flagIconId;
        this.cases = cases;
        this.deaths = deaths;
        this.rating = rating;
        this.note = note;
    }

    public CountryStatistic(CountryStatistic other){
        this.country = other.country;
        this.countryCode = other.countryCode;
        this.flagIconId = other.flagIconId;
        this.cases = other.cases;
        this.deaths = other.deaths;
        this.rating = other.rating;
        this.note = other.note;
    }

    //autogenerated equals method
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CountryStatistic)) return false;
        CountryStatistic that = (CountryStatistic) o;
        return flagIconId == that.flagIconId &&
                cases == that.cases &&
                deaths == that.deaths &&
                Double.compare(that.rating, rating) == 0 &&
                country.equals(that.country) &&
                countryCode.equals(that.countryCode) &&
               note.equals(that.note);
    }

}

